### ISSUE TITLE
nextflow pull -r <branch> fails if master does not include main.nf or nextflow.conf

### ISSUE THREAD

**Issue by nkrumm** [nextflow-io/nextflow#1591]
## Bug report 

When using `nextflow pull <repo> -r <branch>`, the command will fail if the master branch of the repository does not contain `main.nf` or `nextflow.config`
```bash
nextflow pull https://github.com/proychou/hCoV19 -r nextflow-demux-integration
Checking https://github.com/proychou/hCoV19 ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/proychou/hCoV19/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/proychou/hCoV19/contents/main.nf
```

However, the same branch, in a different repository under master works:
```bash
nextflow pull https://github.com/nkrumm/hCoV19-nf -r master
Checking https://github.com/nkrumm/hCoV19-nf ...
downloaded from https://github.com/nkrumm/hCoV19-nf.git - revision: 66ade0195a [master]
```

### Expected behavior and actual behavior
When specifying `-r <branch>` for `nextflow pull`, only the branch given would be pulled, and the command would succeed. There should not be any requirements on the master branch.

### Steps to reproduce the problem

See above. Note that `nextflow list` was empty before I started this.

### Program output 

As far as I can tell these commands are not logged to .nextflow.log

### Environment 

* Nextflow version: = 20.01.0.5264
* Java version: openjdk version "1.8.0_252"
* Operating system: macOS
* Bash version: zsh 5.7.1 (x86_64-apple-darwin19.0)

### additional context

This same issue may also affect the `nextflow run` command if given a branch on a repo where `master` does not have a main.nf or nextflow.config,

**Comment by ebioman** [comment]
We encountered the same issue which makes it really difficult to separate properly e.g. a "master" and "dev" branch as the config file of the "master" branch is messing up the run if variables are potentially differently defined between both branches.

**Comment by chasemc** [comment]
I'm seeing this as well. Looks like the API call might only be looking at the main branch

**Comment by marcadella** [comment]
Why has this issue been closed? It doesn't seem to be solved. When running `docker run -r <branch> repo` I get the following error: `nextflow.exception.AbortOperationException: Remote resource not found: https://gitlab.com/api/v4/projects/uit-sfb%2Fautoget-nextflow/repository/files/main.nf?ref=master`. Why is the API looking at master branch?

V21.10.6.5660

**Comment by gwright99** [comment]
Just so I'm clear here, what was solved by this change? Thus far, we've encountered two flavours of "missing files on master branch" problem:

- `master` branch exists but does not have a `main.nf` and `nextflow.config` in it (because client is using a different branch, e.g. `dev`).
- `master` branch does not exist because the repo is relatively new and uses `main`. The main branch contains a `main.nf` and `nextflow.config`.

#### Questions
1. Are zero, one, or both of these problems solved?
2. For whatever is solved, is that only when trying to retrieve the Nextflow workflow while within Tower or does this now work if I'm using Nextflow on its own?

**Note**: I'm asking because there is a ticket on this in the Nextflow repo, and we have client reports from e-therapeutics, Rijkzwaan, and CEGX (_whom we are meeting next week for another check-in and this issue was reported by them in the Q3 check-in).

**Comment by ebioman** [comment]
Hi I think another directly related and almost worse problem is the fact that elements from master branch override settings in another chosen branch.
E.g. when a Sha value for a container differs in branch master and e.g. dev the one in master will be pulled

**Comment by marcadella** [comment]
@gwright99 Can you maybe share the link of the tracking issue?

**Comment by abhi18av** [comment]
Hi @marcadella , 

Unfortunately, that's a private repo so can't share the link. But as soon as we've addressed it and have updates, we'll share it here.

**Comment by pditommaso** [comment]
This has been solved by https://github.com/nextflow-io/nextflow/pull/2876. Available as of version 22.05.0-edge and later.

**Comment by KOD1S** [comment]
Hi, this issue persists on nextflow version 22.06.1-edge.

**Comment by jorgeaguileraseqera** [comment]
@KOD1S can you say me the provider, please? I tested against Github but maybe we need to review other providers

**Comment by warrenson** [comment]
This seems to still be broken in nextflow 23.04.4 when trying to access an alternate branch on a private/internal GitHub repo.

```
$ nextflow clone -r testnfbranch powerPlant/sandbox
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/powerPlant/sandbox/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/powerPlant/sandbox/contents/main.nf
```

If I add a dummy `main.nf` to the main branch of the repo, then the above command works as expected. I still see the warning about the missing config, but there is no missing `main.nf` error and the correct repo branch is cloned successfully.

**Comment by AGeorge-Hifi** [comment]
Facing same issues with RNAseq pipeline

**Comment by bentsherman** [comment]
@AGeorge-Hifi you misspelled the pipeline repo, it should be `nf-core/rnaseq`
