### ISSUE TITLE
Graceful fallback when `array` is used on unsupported executors

### ISSUE THREAD

**Issue by itrujnara** [nextflow-io/nextflow#5924]
## New feature

Currently, config parsing always fails if the `array` process directive is used in an executor that does not support job arrays (most importantly `local`). It would be reasonable to have Nextflow fall back to running single processes instead and print a warning to `stderr.` If needed, this behavior can be controlled with an environment variable.

## Use case 

Some pipelines have processes that take very little time to run (< 5 minutes). In that case, using job arrays is a reasonable default behavior. However, it is impossible to set directly, as it will fail on executors without job arrays.

## Suggested implementation 

As described above.

**Comment by bentsherman** [comment]
I would just label the processes for which you want to use job arrays and use withLabel to set the array directive for those processes. It's generally better to be specific in that way rather than enabling job arrays across the board

**Comment by itrujnara** [comment]
I'm not sure this fully addresses the issue. If I set the following in the config
```
withLabel: 'very_short' {
    array = 10
}
```
it will still fail if I run the pipeline with the `local` executor. Is there an idiomatic way to have such a pipeline ignore the array directive on a local machine but follow it on a Slurm cluster?

**Comment by bentsherman** [comment]
I assume you have two profiles for local and slurm? In that case you can just put the array config in the slurm profile

**Comment by itrujnara** [comment]
That's the solution I have implemented for the time being. The pipeline is nf-core, so it needs to be as portable as possible. I hoped I could somehow make using arrays the default behavior on grid executors, but it seems it's not possible for the time being.

**Comment by bentsherman** [comment]
I would caution against making job arrays the default across the entire pipeline, because there are cases where it can actually hurt you.

For example, the first step in the pipeline will probably receive a deluge of tasks all at once because it's just loading the inputs. But a later step might receive tasks at a slower rate as some upstream tasks take longer than others. In the latter case, it might not be so important to batch the job submissions if they are already slow, and enabling job arrays might just needlessly delay job submissions while waiting for a full array to submit

That's just my intuition, but in reality it would depend on the actual submit rates vs the capacity of the scheduler. I do wonder whether this issue would come up in practice or not

**Comment by anoronh4** [comment]
@bentsherman regarding the usage of array for a whole pipeline, I’ve noticed that when using the array directive, tasks can stay pending for a long time if the array doesn’t fill up or indefinitely if a poison pill isn’t sent (e.g. with watchPath). It may not matter if array is set for specific processes or for the whole pipeline.

I'm wondering if it might be helpful if array supported a time-based trigger, i.e., submitting whatever’s available after a configurable timeout. That could make it more robust for streaming or continuously monitored inputs. Not sure if it makes sense to leverage existing options like executor.pollInterval or executor.getQueueStatInterval, or if it would make more sense to create a new option. That would make it so that you could use array across the whole pipeline -- but of course, it wouldn't directly solve @itrujnara 's issue of a fallback for unsupported executors. 

Just wanted to share this idea and see if others would be helped by this same solution.

**Comment by bentsherman** [comment]
> tasks can stay pending for a long time if the array doesn’t fill up

This is an inherent trade-off with job arrays, you can either submit larger arrays and wait more or submit smaller arrays and wait less. This is why I advise to tune the array size for each process based on how frequently you expect the process to receive inputs.

> or indefinitely if a poison pill isn’t sent (e.g. with watchPath)

Indeed, and the same problem exists with any "blocking" operator such as `collect`. For this reason there is a big warning in the [docs](https://nextflow.io/docs/latest/reference/channel.html#watchpath) for `watchPath` that you should use an operator like `take` or `until` if you don't want your pipeline to run forever. I would advise the same when using `watchPath` with array jobs

**Comment by anoronh4** [comment]
but what if i do want my pipeline to run forever but not hang on process tasks that are ready to run, forever or until new inputs come through watchPath?

or what if I am not using watchpath, but I still don't want processes to hang for an extremely long time while waiting for the array size to fill up?

**Comment by johnoooh** [comment]
Hey Ben,  I implemented what Anne Marie and I were thinking of in my fork.  It does what we are asking, would you like to take a look?

https://github.com/johnoooh/nextflow/blob/feature/slurm_array_timer/modules/nextflow/src/main/groovy/nextflow/processor/TaskArrayCollector.groovy

With this, if you have 120 jobs and an array size of 100, the last 20 jobs will be submitted 5 minutes after the first job over 100 is received to the task array.

**Comment by johnoooh** [comment]
Here is a dummy script to test this, just replace the partition with your slurm partition. 

```

#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

params.array_size = 10
params.sleep_time = 30
params.outdir = "results"
params.input_dir = "input_files"
params.partition = 'testpartition'

process DUMMY_TASK {
    executor 'slurm'
    queue 'cmobic_cpu'
    array params.array_size
    cpus 1
    memory '1 GB'
    time '5m'
    debug true
    tag "task_${task.index}"
    
    input:
    path input_file
    
    output:
    path "${input_file.baseName}_output.txt"
    
    script:
    """
    echo "Processing ${input_file} started at \$(date)" > ${input_file.baseName}_output.txt
    echo "Host: \$(hostname)" >> ${input_file.baseName}_output.txt
    echo "SLURM_ARRAY_JOB_ID: \${SLURM_ARRAY_JOB_ID:-'not_set'}" >> ${input_file.baseName}_output.txt
    echo "SLURM_ARRAY_TASK_ID: \${SLURM_ARRAY_TASK_ID:-'not_set'}" >> ${input_file.baseName}_output.txt
    
    # Simulate processing
    sleep ${params.sleep_time}
    
    echo "Processing ${input_file} completed at \$(date)" >> ${input_file.baseName}_output.txt
    """
}

workflow {
    input_files = Channel.watchPath("${params.input_dir}/*.txt")

    DUMMY_TASK(input_files)

    DUMMY_TASK.out.view { file ->
        "[${new Date().format('HH:mm:ss')}] Processed: ${file.name}"
    }
}
```

And while that is running, in the same directory run this oneliner:
 `for i in {1..16};do echo "Input data for task $i" > input_files/task_${i}.txt && echo "Created input_files/task_${i}.txt"; sleep .5;done`

The first 10 jobs are submitted as an array job as expected.  The next 6 jobs are added into the task array.  Then, the time specified by executorSubmitTimeout later passes.  At this point the remaining 6 jobs are put into a job array and submitted to the cluster.

Note I didnt configure executorSubmitTimeout as a configurable parameter yet so it just uses whatever I set as the default. 

Maybe I'll just open a new issue for this.

**Comment by bentsherman** [comment]
Before we get into solutions, I need to understand your use case

> but what if i do want my pipeline to run forever but not hang on process tasks that are ready to run, forever or until new inputs come through watchPath?

I would say that Nextflow isn't designed to *actually* run forever. The intention behind watchPath is that you will limit it somehow, most likely using `take` or `until`.

For example, you could have some external process (or even the pipeline itself) write a "done" file into the watchPath directory after some duration and use the `until` operator to stop the watchPath once this "done" file is received.

So are you actually running a pipeline forever? Surely you are eventually stopping it somehow?

> or what if I am not using watchpath, but I still don't want processes to hang for an extremely long time while waiting for the array size to fill up?

If you feel that tasks are waiting too long to be submitted in a job array, that is an indication that your array size is too large or that you might not need job arrays at all for that process

As I understand it, and i could be wrong, the purpose of job arrays is solely to reduce the frequency of job submissions. So if jobs are already coming in at a trickle for a particular process, you might not need job arrays in the first place, at least for that process

**Comment by anoronh4** [comment]
Certain workflows we do run continuously and watchPath is used to monitor files for any incoming inputs. Perhaps it is not intended that way but the way it's designed has been working well for us. It simplifies automation for us because instead of kicking off a separate run for each new sample, we keep using the same run. 

I don't know that I agree that it's only when an array is too big. The array size can be very small and have this issue. if an array has not reached the desired size and is waiting on upstream processes to complete, all other jobs in the array are waiting for that upstream job to complete for a job that could take hours, and meanwhile our goal is just to get around 100 RPC/min. as it stands, array will work well when we initialize a run and have a deluge of jobs, but later on in the same run the volume can be much lower and get stuck.

**Comment by bentsherman** [comment]
If the issue is that there are many samples to process at the beginning and afterwards samples arrive slowly (sounds like the orthogonal case to what I described [here](https://github.com/nextflow-io/nextflow/issues/5924#issuecomment-2776234218)), maybe the solution is to just limit the [submit rate](https://nextflow.io/docs/latest/reference/config.html#executor) directly with `executor.submitRateLimit`

**Comment by anoronh4** [comment]
we’ve tested and confirmed that the current options (submitRateLimit, queueSize) are somewhat serviceable, but it’s not ideal for our use cases and leads to inefficiencies and is limited in flexibility. we will be processing a high volume of samples very slowly, since submitRateLimit must be lower than the RPC quota of the SLURM scheduler. If we use it with arrays at the same time that helps, but then we run into issues of jobs being delayed for very long periods of time, with or without watchPath. i believe the change that @johnoooh and i are proposing directly addresses some of the limitations of the job array. plus, this change would make it more feasible for a user to apply array as a default across the pipeline.

**Comment by bentsherman** [comment]
I think I understand. Thanks for explaining your situation. I will review your solution when I have some time and consider how we might incorporate it

**Comment by anoronh4** [comment]
thank you! we appreciate you looking into this.
